/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./blog/templates/**/*.html",
    "./blog/templates/*.html",
    "./blog/static/blog/js/**/*.js",
  ],
  theme: {
    extend: {
      fontFamily: {
        seasons: 'var(--font-seasons)',
        inter: 'var(--font-inter)',
        playfair: 'var(--font-playfair)',
        roboto: 'var(--font-roboto)',
        merriweather: 'var(--font-merriweather)',
      },
      fontSeasons: 'serif',
      fontInter: 'Inter, sans-serif',
      fontPlayfair: '"Playfair Display", serif',
      fontRoboto: 'Roboto, sans-serif',
      fontMerriweather: 'Merriweather, serif',
      colors: {
        byline: {
          dark: '#1a1a2e',
          red: '#B91C1C',
          light: '#FEE2E2',
          yellow: '#FEB300'
        },
      },
      keyframes: {
        scroll: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        fadeIn: {
          '0%': { opacity: 0, transform: 'translateY(-10px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' }
        }
      },
      animation: {
        scroll: 'scroll 40s linear infinite',
        fadeIn: 'fadeIn 0.8s ease-out forwards'
      },
    },
  },
  safelist: [
    'bg-brand', 'text-brand', 'md:grid-cols-3', 'lg:flex', 
    'hidden', 'block', 'flex', 'grid', 'col-span-2',
    'text-red-600', 'hover:text-red-600', 'bg-red-600', 'border-red-600',
    'text-black', 'bg-black', 'border-black',
    'text-white', 'bg-white', 'border-white',
    'text-gray-500', 'bg-gray-500', 'border-gray-500',
    'text-gray-600', 'bg-gray-600', 'border-gray-600',
    'text-gray-700', 'bg-gray-700', 'border-gray-700',
    'text-gray-800', 'bg-gray-800', 'border-gray-800',
    'text-gray-900', 'bg-gray-900', 'border-gray-900',
    'group-hover:opacity-100', 'group-hover:w-full',
    'hover:text-black', 'hover:bg-white', 'hover:border',
    'transition', 'transition-all', 'transition-colors', 'transition-transform',
    'duration-200', 'duration-300', 'ease-in-out',
    'shadow', 'shadow-lg', 'shadow-md', 'shadow-sm',
    'rounded', 'rounded-lg', 'rounded-xl', 'rounded-full',
    'border', 'border-t', 'border-b', 'border-l', 'border-r',
    'border-2', 'border-4',
    'p-2', 'p-3', 'p-4', 'p-6',
    'py-1', 'py-2', 'py-3', 'py-4', 'py-6',
    'px-2', 'px-3', 'px-4', 'px-6',
    'm-2', 'm-4', 'm-6',
    'my-2', 'my-4', 'my-6',
    'mx-2', 'mx-4', 'mx-6',
    'mt-1', 'mt-2', 'mt-3', 'mt-4', 'mt-6', 'mt-10', 'mt-16',
    'mb-1', 'mb-2', 'mb-3', 'mb-4', 'mb-6', 'mb-10', 'mb-12', 'mb-16',
    'ml-2', 'ml-4', 'ml-6',
    'mr-2', 'mr-4', 'mr-6',
    'w-full', 'w-1/2', 'w-1/3', 'w-2/3', 'w-1/4', 'w-3/4',
    'h-full', 'h-48', 'h-64',
    'max-w-7xl', 'max-w-4xl', 'max-w-md', 'max-w-sm',
    'max-h-85vh', 'max-h-350px',
    'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4',
    'sm:grid-cols-1', 'sm:grid-cols-2', 'sm:grid-cols-3', 'sm:grid-cols-4',
    'md:grid-cols-1', 'md:grid-cols-2', 'md:grid-cols-3', 'md:grid-cols-4',
    'lg:grid-cols-1', 'lg:grid-cols-2', 'lg:grid-cols-3', 'lg:grid-cols-4',
    'gap-2', 'gap-4', 'gap-6', 'gap-10',
    'space-y-2', 'space-y-4', 'space-y-6',
    'space-x-2', 'space-x-3', 'space-x-4', 'space-x-6',
    'items-center', 'items-start', 'items-end',
    'justify-center', 'justify-between', 'justify-around',
    'flex-col', 'flex-row',
    'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl',
    'font-semibold', 'font-bold', 'font-medium',
    'font-playfair', 'font-inter', 'font-roboto', 'font-merriweather', 'font-seasons',
    // Font family utilities
    { pattern: /^font-(playfair|inter|roboto|merriweather|seasons)$/ },
    'uppercase', 'lowercase', 'capitalize',
    'text-center', 'text-left', 'text-right', 'text-justify',
    'truncate', 'break-words', 'whitespace-nowrap',
    'opacity-0', 'opacity-50', 'opacity-75', 'opacity-100',
    'z-10', 'z-20', 'z-30', 'z-40', 'z-50',
    'absolute', 'relative', 'fixed', 'sticky',
    'top-0', 'bottom-0', 'left-0', 'right-0',
    'overflow-hidden', 'overflow-x-hidden', 'overflow-y-auto', 'overflow-y-scroll',
    'object-cover', 'object-contain',
    'inline-block', 'inline-flex',
    'visible', 'invisible',
    'select-none',
    'underline', 'no-underline',
    'italic', 'not-italic',
  ],
  plugins: [],
}