# Generated by Django 5.2.4 on 2025-07-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_opinion',
            field=models.BooleanField(default=False),
        ),
    ]
