# Generated by Django 5.2.4 on 2025-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authorImage',
            field=models.ImageField(default='avtar.jpg', upload_to='author_images/'),
        ),
    ]
